### ISSUE TITLE
CC less than one?

### ISSUE THREAD

**Issue by michaelradionov** [Halleck45/ast-metrics#69]
Hello, Jean-François. I love your tool AST metrics, many thanks for that. I have a question about. How could Cyclomatic Complexity be less than 1? I see CC less than 1 both per method and per class.
![Снимок экрана 2024-11-13 в 18 42 41](https://github.com/user-attachments/assets/c7ae1355-1a7f-4972-8d9d-5d55745196ee)

**Comment by Halleck45** [comment]
Greetings! 

I suspect that there may be a problem with the results aggregation (which calculates the distribution). Could I request a sample of the code that generated this output?"

**Comment by michaelradionov** [comment]
I think the problem might be that this tool assumes that code with no "if" has zero CC. For example, this piece of code results this report. Maybe result should be 1, not 0 in this case?
![Снимок экрана 2024-11-13 в 19 17 16](https://github.com/user-attachments/assets/26992e04-ba61-44b6-b1fe-994739ceb152)
![Снимок экрана 2024-11-13 в 19 21 41](https://github.com/user-attachments/assets/15aec94e-7bd5-456a-bdc4-e595e9650584)

**Comment by Halleck45** [comment]
Indeed, there are 2 issues:

1. The function itself is not counted in the complexity calculation. This is fixed with this PR: https://github.com/Halleck45/ast-metrics/pull/72

2. (under analysis, to be confirmed) When calculating the average, we do not distinguish between interface methods and class methods. This can lead to averages below 0. I will investigate how to solve this point.

**Comment by michaelradionov** [comment]
Hi. Thanks for answer, I just updated to latest release but I still getting CC less than one. Also Risk and Instability now return 0.
<img width="1146" alt="Снимок экрана 2024-12-06 в 17 26 13" src="https://github.com/user-attachments/assets/bfd993e7-b432-4106-b697-dc4dbbddf583">

**Comment by Halleck45** [comment]
Hi,

I think this issue is outdated. Feel free to reopen it if needed.
